apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-storage

resources:
  - testuser.yaml
  - produser.yaml
  - devuser.yaml

commonLabels:
  app: ceph-rgw-users
  managed-by: gitops
